spring:
  application:
    name: spring-transaction
  datasource:
    db1:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://127.0.0.1:3306/spring_transaction
      username: root
      password: root
      hikari:
        auto-commit: false
        pool-name: HikariCP1
    db2:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://127.0.0.1:3306/spring_transaction2
      username: root
      password: root
      hikari:
        auto-commit: false
        pool-name: HikariCP2
logging:
  level:
    org:
      apache:
        ibatis: debug
      mybatis: debug
      com:
        example:
          spring_transaction: debug
      springframework:
        transaction:
          interceptor: DEBUG
          support: DEBUG
    sql: debug
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    cache-enabled: false
  db1:
    mapper-locations: classpath:mapper/user/*.xml
    type-aliases-package: com.example.spring_transaction.user.entity
  db2:
    mapper-locations: classpath:mapper/food/*.xml
    type-aliases-package: com.example.spring_transaction.food.entity