spring:
  application:
    name: spring-transaction
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/spring_transaction
    username: root
    password: toorroot
  jpa:
    hibernate:
      ddl-auto: update # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
logging:
  level:
    org:
      springframework:
        transaction: DEBUG
        orm:
          jpa: DEBUG
    sql: debug
