spring:
  application:
    name: spring-transaction
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/spring_transaction
    username: root
    password: toorroot
logging:
  level:
    org:
      springframework:
        transaction: DEBUG
    sql: debug
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.example.spring_transaction.**.entity